{
  "comments": [
    {
      "key": {
        "uuid": "cd0889ac_f18d1440",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 7,
      "author": {
        "id": 5015
      },
      "writtenOn": "2017-02-27T04:02:55Z",
      "side": 1,
      "message": "Fixes #284",
      "revId": "1fe935653c07eba8bdd9a2aa18fb51826fb3c2d3",
      "serverId": "0759ed4b-3fdc-34dc-866b-f2e708168c03",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "b07f4d78_7534620a",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 7,
      "author": {
        "id": 5389
      },
      "writtenOn": "2017-02-27T04:04:02Z",
      "side": 1,
      "message": "It doesn\u0027t, unfortunately. Your test failures appear unrelated.",
      "parentUuid": "cd0889ac_f18d1440",
      "revId": "1fe935653c07eba8bdd9a2aa18fb51826fb3c2d3",
      "serverId": "0759ed4b-3fdc-34dc-866b-f2e708168c03",
      "unresolved": true
    }
  ]
}