{
  "comments": [
    {
      "key": {
        "uuid": "7c371b6c_7ef57f5b",
        "filename": "bind/bind.go",
        "patchSetId": 1
      },
      "lineNbr": 59,
      "author": {
        "id": 5005
      },
      "writtenOn": "2016-05-27T02:47:27Z",
      "side": 1,
      "message": "i don\u0027t see the value of this field.",
      "revId": "824968c5be2caa8175a3e3e74c12e11db5e28372",
      "serverId": "0759ed4b-3fdc-34dc-866b-f2e708168c03",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "7c371b6c_9efe4344",
        "filename": "bind/bind.go",
        "patchSetId": 1
      },
      "lineNbr": 221,
      "author": {
        "id": 5005
      },
      "writtenOn": "2016-05-27T02:47:27Z",
      "side": 1,
      "message": "that\u0027s a for loop if i ever saw one",
      "revId": "824968c5be2caa8175a3e3e74c12e11db5e28372",
      "serverId": "0759ed4b-3fdc-34dc-866b-f2e708168c03",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "7c371b6c_1e91d30b",
        "filename": "bind/bind.go",
        "patchSetId": 1
      },
      "lineNbr": 242,
      "author": {
        "id": 5005
      },
      "writtenOn": "2016-05-27T02:47:27Z",
      "side": 1,
      "message": "if ping failed, you\u0027ll leave a dial hanging that others might find and retry on, which seems wrong. ditt of err !\u003d nil. this is close but i think it leaves the system in a bad state if the dial fails with concurrent callers.\n\nif that\u0027s not true, this is still too complicated for me to understand.",
      "revId": "824968c5be2caa8175a3e3e74c12e11db5e28372",
      "serverId": "0759ed4b-3fdc-34dc-866b-f2e708168c03",
      "unresolved": false
    }
  ]
}