{
  "comments": [
    {
      "key": {
        "uuid": "e82ee08f_54693df4",
        "filename": "directory/testdir/directory.go",
        "patchSetId": 4
      },
      "lineNbr": 285,
      "author": {
        "id": 5015
      },
      "writtenOn": "2016-04-17T18:22:06Z",
      "side": 1,
      "message": "As innocent as this might look, this \"broke\" testuser/user_test. But not because this is wrong.  Instead, test_user was not setting up the username in the context and hence the testdir didn\u0027t know who was calling it. Until now, it had no reason to know since it wasn\u0027t checking permissions. \n\nFixing user_test my testenv CL.",
      "revId": "b0f4288bdad5e3d430b820adf71e362d793edbb2",
      "serverId": "0759ed4b-3fdc-34dc-866b-f2e708168c03",
      "unresolved": false
    }
  ]
}